### PR TITLE
Add interfaces for client and message

### PR DESCRIPTION
**Pull request by 4c0n**
By adding interfaces the classes can be mocked in the tests of implementing projects/packages.
Alternatively the `final` keyword could be removed.

What do you think?

### CODE REVIEW

**Comment by 4c0n** [comment]
@soullivaneuh hope you are doing okay?

**Comment by soullivaneuh** [comment]
@4c0n Sorry for the missing reply, I missed the notification for this PR.

Travis does not seems to work. Could you try to push again in order to trigger the job?

**Comment by 4c0n** [comment]
@soullivaneuh No problem :) I tried pushing again, but since there are no new commits, it didn't do much.

Could you try logging into Travis and manually restarting the build? I cannot do that because I don't have access for your repository.

**Comment by soullivaneuh** [comment]
@4c0n Indeed, the status was not updated.

The lint job is failing, could you please run php-cs-fixer?

**Comment by 4c0n** [comment]
@soullivaneuh Thanks for looking into the failed build. I have now ran php-cs-fixer and the build is now succesful.

**Review by soullivaneuh — APPROVED** [review]

**Comment by soullivaneuh** [comment]
Merged and released: https://github.com/nexylan/slack/releases/tag/v3.1.0

Thanks for you contribution. :+1:

**Pull request merged**
